[package]
name = "librb-http"
version = "0.1.0"
authors = ["Diego Fernández Barrera <bigomby@gmail.com>"]
build = "build.rs"

[lib]
name = "rbhttp"
crate-type = ["staticlib"]

[build-dependencies]
gcc = "0.3.51"

[dependencies]
libc = "0.2.23"
